package com.spd.yinlianpay.trade;

/**
 * 项目名称：GDRCC
 * 类描述：错误信息类
 * 创建人：GY
 * 创建时间：2016/12/27 15:08
 * 修改人：GY
 * 修改时间：2016/12/27 15:08
 * 修改备注：
 */


public  interface ErrorMsgType {

    int ERR_DEFINE_START=0x00;

    //EMVLIB返回值定义
    int 	EMV_OK=0x00;
    int 	ERR_EMVRSP=-1;//返回码错误
    int 	ERR_APPBLOCK=-2;//应用已锁
    int 	ERR_NOAPP=-3;//卡片里没有EMV应用
    int  	ERR_USERCANCEL=-4;//用户取消当前操作或交易
    int 	ERR_TIMEOUT=-5;//用户操作超时
    int 	ERR_EMVDATA=-6;//卡片数据错误
    int 	ERR_NOTACCEPT=-7;//交易不接受
    int 	ERR_EMVDENIAL=-8;//交易被拒绝
    int 	ERR_KEYEXP=-9;//密钥过期
    int 	ERR_NOPINPAD=-10;//没有密码键盘或键盘不可用
    int 	ERR_NOPIN=-11;//没有密码或用户忽略了密码输入
    int 	ERR_CAPKCHECKSUM=-12;//认证中心密钥校验和错误
    int 	ERR_NOTFOUND=-13;//没有找到指定的数据或元素
    int 	ERR_NODATA=-14;//指定的数据元素没有数据
    int 	ERR_OVERFLOW=-15;//内存溢出
    int 	ERR_NOTRANSLOG=-16;//无交易日志
    int 	ERR_NORECORD=-17;//无记录
    int 	ERR_NOLOGITEM=-18;//目志项目错误
    int 	ERR_ICCRESET=-19;//IC卡复位失败
    int 	ERR_ICCCMD=-20;//IC命令失败
    int 	ERR_ICCBLOCK=-21;//IC卡锁卡
    int 	ERR_ICCNORECORD=-22;//IC卡无记录6A83
    int 	ERR_GENAC1_6985=-23;//GENAC命令返回6985
    int 	ERR_USECONTACT=-24;//非接失败，改用接触界面
    int 	ERR_APPEXP=-25;//qPBOC卡应用过期
    int 	ERR_BLACKLIST=-26;//qPBOC黑名单卡
    int 	ERR_GPORSP=-27;//errfromGPO
    int 	ERR_USEMAG=-28;//非接中止，改用磁卡
    int 	ERR_TRANSEXCEEDED=-29;//非接交易超限
    int 	ERR_QPBOCFDDAFAIL=-30;//非接qPBOCfDDA失败

    int 	EMV_DATA_EXIST=-31;//
    int 	EMV_FILE_ERR=-32;//
    int 	EMV_PIN_BLOCK=-33;//PIN重试次数超限



    int 	SUCCESS_SELNOTENTER=0x01;//选择了;但是没有按确认键
    int 	FLAG_FIRSTRUN=0x02;//机器是首次运行
    int 	FLAG_NOTFIRSTRUN=0x03;//机器不是首次运行

        	//交易类型范围定义
    int 	EVENT_TRANSTYPE=0x04;//交易类型
    int 	EVENT_MENUTYPE=0x05;//菜单类型
    int 	EVENT_OTHERTYPE=0x06;//其他类型
    int 	ENENT_NEXTEVENTTYPE=0x07;//下一步事件类型


    int 	SUCCESS=0x00;
    int 	SUCCESS_TRACKDATA=0x00;
    int 	OK=0x00;

    //普通错误信息表
    int 	ERR_CANCEL =1;
    int 	ERR_END=2;
    int 	ERR_DATASAVE=3;
    int 	ERR_DRIVER=4;
    int 	ERR_OSFUNC=5;
    int 	ERR_NOTPROC=6;
    int ERR_UNKNOWNTRANTYPE=7;
    int 	ERR_AMOUNTZERO=9;
    int 	ERR_RESETDATASAVEDATA=10;
    int 	ERR_DIAL=11;
    int 	ERR_DIAL_BUSY=12;
    int 	ERR_DIAL_NO_TONE=13;
    int 	ERR_DIAL_NO_CARRIER=14;
    int 	ERR_DIAL_LINE_BUSY=15;
    int 	ERR_HOSTCODE=16;
    int 	ERR_HOSTINF=17;//44域返回错误显示信息
    int 	ERR_DATAINVALID=18;
    int 	ERR_INVALIDXDATAPAGE=19;
    int 	ERR_INVALIDTRANS=20;
    int 	ERR_TRANSFILEFULL=21;
    int 	ERR_NOPSAM=22;
    int 	ERR_NOTVALIDPSAM=23;
    int 	ERR_NOOLDTRANS=24;
    int 	ERR_PRINT=25;
    int 	ERR_ALREADYVOID=26;
    int 	ERR_NOTRANS=27;
    int 	ERR_CommPortOpenErr=28;
    int 	ERR_TRANS_UNKNOWOPERTYPE=29;
    int 	ERR_TRANS_UNKNOWTRANSTYPE=30;
    int 	ERR_NOTZEROAMOUNT=31;
    int 	ERR_VERIFY_PINONE=32;
    int 	ERR_VERIFY_PINTOW=33;
    int 	ERR_VERIFY_PINTHREE=34;
    int 	ERR_NOTSUPPORTSALE=35;
    int 	ERR_NOTSUPPORTPREAUTH=36;
    int 	ERR_NOTLOGON=37;
    int 	ERR_LOGONBATCH=38;
    int 	ERR_PLEASESETTLEMENT=39;
    int 	ERR_ADMINISNOTEXIST=40;
    int 	ERR_KEY=41;
    int 	ERR_ENCRYPTION_DEVICE=42;
    int 	ERR_NOFUNCT=43;
    int 	ERR_NOINPUTSUPPORT=44;
    int 	ERR_LINEISBUSY=45;
    int 	ERR_FREERESPONSE=46;
    int 	ERR_COMMINTERRUPT=47;
    int 	ERR_OTHERLINEBUSY=48;
    int 	ERR_CONNECTSUCCESS=49;
    int 	ERR_CONNECTTELLINE=50;
    int 	ERR_MODEM=51;
    int 	ERR_DIALING=52;
    int 	ERR_HOSTTIMEOUT=53;
    int 	ERR_HOSTNOTRSP=54;
    int 	ERR_HOSTNOTRSPEX=55;
    int 	ERR_NOTDIALTONE=56;
    int 	ERR_CONNECTION=57;
    int 	ERR_DIALUPREJECTED=58;
    int 	ERR_TELLINEBUSY=59;
    int 	ERR_AMOUNTERR=60;
    int 	ERR_WRITEMEMORY=61;
    int 	ERR_CHECKSECRET=62;
    int 	ERR_MODIFYSECRET=63;
    int 	ERR_CARDLOCK=64;
    int 	ERR_NOTSAFT=65;//不满足安全状态
    int 	ERR_FILENOTFOUND=66;//文件未找到
    int 	ERR_RECORDNOTFOUND=67;//记录未找到
    int 	ERR_NOTUSEFUNC	=68	;//不支持此功能
    int 	ERR_LESSBALANCE=69;//余额不足
    int 	ERR_FULLCOUNT=70;//计数器已满
    int 	ERR_NOKEYINDEX=71;//密钥索引不支持
    int 	ERR_MACERROR=72;//MAC无效
    int 	ERR_CASENOTFULL=73;//使用条件不满足
    int 	ERR_BALANCEEX=74;//充值后余额超限
    int 	ERR_KNOWERROR=75;//卡操作失败
    int 	ERR_EXPIREDATE=76;//有效期已过或无效
    int 	ERR_CARDCRC=77;
    int 	ERR_TAGNOTEXIST=78;
    int 	ERR_PLSLOADPARAM=79;
    int 	ERR_INTERNOTTIP=80;
    int 	ERR_TRANSNOTSUP=81;
    int 	ERR_INVAILDAMOUNT=82;
    int 	ERR_TRANSADJUSTED=83;
    int 	ERR_TRANSTIEMOUT=84;
    int 	ERR_FORMAT=85;
    int 	EMV_ERRDATALEN=86;
    int 	EMV_ERRTAG=87;
    int 	EMV_ERRLENGTH=88;
    int 	EMV_ERRAPPNUM=89;
    int 	EMV_ERRDATA=90;
    int 	EMV_SETTLEFIRST=91;
    int 	EMV_NOSUCHTRACE=92;
    int 	EMV_DATAOVERFLOW=93;
    int 	EMV_TRANSFAIL=94;
    int 	ERR_OLDNOTVOID=95			;
    int 	ERR_USEICCARDFIRST=96;
    int 	ERR_TRANSNOTFIND=97;
    int 	ERR_LASTSETTLENOTEXIST=98;
    int 	ERR_PRN_BUSY=99;
    int 	ERR_PRN_NOPAPER=100;
    int 	ERR_PRN_DATAERR=101;
    int 	ERR_PRN_FAULT=102;
    int 	ERR_PRN_TOOHEAT=103;
    int 	ERR_PRN_UNFINISHED=104;
    int 	ERR_PRN_NOFONTLIB=105;
    int ERR_PRN_BUFFOVERFLOW=106;
    int 	ERR_ISO83=107;
    int 	ERR_ISO8583_INVALIDVALUE=108;
    int 	ERR_ISO8583_PACKAGETID=109;
    int 	ERR_ISO8583_INVALIDBIT=110;
    int 	ERR_ISO8583_INVALIDPACKLEN=111;
    int 	ERR_ISO8583_OVERBITBUFLIMIT=112;
    int 	ERR_ISO8583_BITNOTEXIST=113;
    int 	ERR_ISO8583_INVALIDPARAM=114;
    int 	ERR_ISO8583_NODATAPACK=115;
    int 	ERR_ISO8583_OVERBUFLIMIT=116;
    int 	ERR_ISO8583_INVALIDBITATTR=117;
    int 	ERR_ISO8583_UNPACKDATA=118;
    int 	ERR_ISO8583_SETBITLEN=119;
    int 	ERR_ISO8583_COMPARE=120;
    int 	ERR_ISO8583_MACERROR=121;
    int 	ERR_ISO8583_MSGID=122;
    int 	ERR_ISO8583_INVALIDLEN=123;
    int 	ERR_UTIL_OVERBUFLIMIT=124;
    int 	ERR_MSG_INVALIDINDEX=125;
    int 	ERR_MSG_INVALIDVALUE=126;
    int 	ERR_MAG_TRACKDATA=127;
    int 	ERR_SANDMAGCARD=128;
    int 	ERR_TRANS_UNKNOWNACCTYPE=129;
    int 	ERR_TRANS_UNKNOWNPACKAGETYPE=130;
    int 	ERR_TRANS_SETTLE=131;
    int 	ERR_TRANS_SAVEINDEX=132;
    int 	ERR_TRANS_CANNOTADJUST=133;
    int 	ERR_COMMS_SENDCHAR=134;
    int 	ERR_COMMS_RECVCHAR=135;
    int 	ERR_YITIHUATRANS=136;//一体化交易出错
    int 	ERR_COMMS_PROTOCOL=137;
    int 	ERR_COMMS_RECVBUFFOVERLIMIT=138;
    int 	ERR_COMMS_RECVTIMEOUT=139;
    int 	ERR_COMMS_LRC=140;
    int 	ERR_LOSE_PACKAGE=141;
    int 	ERR_COMMS_ERRTPDU=142;
    int 	ERR_COMMS_NOMAC=143;
    int 	ERR_NEEDLOGONONLINE=144;
    int 	ERR_SUPER_PASS=145;
    int 	ERR_MANAGER_PASS=146;
    int 	ERR_WORKSWITCH=147;
    int 	ERR_CASH_EXIST=148;
    int 	ERR_CASH_NOTEXIST=149;
    int 	ERR_CASH_PASS=150;
    int 	ERR_ADMINNOTQUXIAN=151;
    int 	ERR_CASH_FILEFULL=152;
    int 	ERR_CASH_NOTLOGON=153;
    int 	ERR_CASH_ALREADYLOGON=154;
    int 	ERR_DISH_EXIST=155;
    int 	ERR_DISH_NOTEXIST=156;
    int 	ERR_DISH_AMOUNT=157;
    int 	ERR_DISH_FILEFULL=158;
    int 	ERR_TRANSEMPTY=159;
    int 	ERR_OFFLINESETTLETRANSEMPTY=160;
    int 	ERR_SETTLE_FIRST=161;
    int 	ERR_FALLBACK=162;
    int 	ERR_OFFLINE=163;
    int 	ERR_SYS_CASHIERNO=164;
    int 	ERR_READANDWRITEICCARD=165;
    int 	ERR_EXPIREDATECARD=166;
    int 	ERR_ICCARD=167;
    int 	ERR_CHECKAOUNMT=168;
    int 	ERR_CAPKCHECK=169;
    int 	ERR_RECVMAXLEN=170;
    int 	ERR_TAGLEN=171;
    int 	ERR_TAGVAL=172;
    int 	ERR_COMMANDBYTE=173;
    int 	ERR_COMMINIT=174;
    int 	ERR_TAGDATA=175;
    int 	ERR_NOLASTSETTLE=176;
    int 	ERR_CARDNO=177;
    int 	ERR_OLDTRANS=178;
    int 	ERR_BALANCE=179;
    int 	ERR_MULTICARD=180;
    int 	ERR_SAVEKEY=181;
    int 	ERR_PINKEY=182;
    int 	ERR_MACKEY=183;
    int 	ERR_MSRKEY=184;//磁道密钥检验错
    int 	ERR_ENCRYPTKEY=185;
    int 	ERR_MASTERKEY=186;
    int 	ERR_WRITEFILE=187;
    int 	ERR_EXITAPP=188;
    int 	ERR_MDATE=189;
    int 	ERR_BLUETOOTHINITERR=190;//蓝牙初始化失败
    int 	ERR_BLUETOOTH_DISCOVERABLERR=191;
    int 	ERR_BLUETOOTH_SETINFOERR=192;
    int 	ERR_BLUETOOTH_GETINFOERR=193;
    int 	ERR_KEY_A0=194;
    int 	ERR_PROMISSORY=195;
    int 	ERR_CTCAMOUNT=196;
    int 	ERR_BLACKPARAM=197;
    int 	EMV_ADDCAPKXORERR=198;
    int 	EMV_ADDCAPKERR=199;
    int 	EMV_ADDAIDERR=200;
    int 	ERR_ICCBLOCKEX=201;
    int 	ERR_APPBLOCKEX=202;
    int 	ERR_ICCDATA=203;
    int 	ERR_EMVRSPEX=204;
    int 	ERR_NOAPPEX=205;
    int 	ERR_USERCANCELEX=206;
    int 	ERR_TIMEOUTEX=207;
    int 	ERR_EMVDATAEX=208;
    int 	ERR_ICCCOMAND=209;//IC卡命令错误
    int 	ERR_NOTACCEPTEX=210;
    int 	ERR_EMVDENIALEX=211;
    int 	ERR_KEYEXPEX=212;
    int 	ERR_NOPINPADEX=213;
    int 	ERR_NOPINEX=214;
    int 	ERR_CAPKCHECKSUMEX=215;
    int 	ERR_NETKEY=216;//网络密钥错;重新签到.
    int 	ERR_MODIBATCH=217;
    int 	ERR_NOTFOUNDEX=218 ;
    int 	ERR_NODATAEX=219;
    int 	ERR_OVERFLOWEX=220;
    int 	ERR_NOTRANSLOGEX=221;
    int 	ERR_NORECORDEX=222;
    int 	ERR_NOLOGITEMEX=223;
    int 	ERR_ICCRESETEX=224;
    int 	ERR_ICCCMDEX=225;
    int 	ERR_ICCNORECORDEX=226;
    int 	ERR_GENAC1_6985EX=227;
    int 	ERR_USECONTACTEX=228;
    int 	ERR_APPEXPEX=229;
    int 	ERR_BLACKLISTEX=230;
    int 	ERR_GPORSPEX=231;
    int 	ERR_TRANSEXCEEDEDEX=232;
    int 	ERR_SAFEPSW=233;
    int 	ERR_NOTPHONECARD=234;
    int 	ERR_OPERDATETIME=235;
    int 	ERR_TMSDOWNLAOD=236;
    int 	MENUSTACKERR_ISFULL=237;//MENU堆栈已满
    int 	MENUSTACKERR_ISEMPTY=238;//MENU堆栈为空
    int 	ERR_APP_TIMEOUT=239;//超时
    int 	ERR_WLS=240;
    int 	ERR_WLS_NORSP=241;
    int 	ERR_WLS_RSP=242;
    int 	ERR_WLS_NOSIM=243;
    int 	ERR_WLS_NEEDPIN=244;
    int 	ERR_WLS_NEEDPUK=245;
    int 	ERR_WLS_SIMBLOCKED=246;
    int 	ERR_WLS_SIM=247;
    int 	ERR_WLS_PIN=248;
    int 	ERR_WLS_PARAM=249;
    int 	ERR_WLS_SNLTOOWEAK=250;
    int 	ERR_WLS_LINKCLOSED=251;
    int     ERR_WLS_LINKOPENED=252;
    int 	ERR_WLS_LINKOPENING=253;
    int 	ERR_WLS_TCPCLOSED=254;
    int 	ERR_WLS_TCPOPENED=255;
    int 	ERR_WLS_TCPOPENING=256;
    int 	ERR_WLS_ATTACHED=257;
    int 	ERR_WLS_DETTACHED=258;
    int 	ERR_WLS_UNKNOWNTYPE=259;
    int 	ERR_WLS_DIALING=260;
    int 	ERR_WLS_PORT=261;
    int 	ERR_WLS_PORTINUSE=262;
    int 	ERR_WLS_DETECT=263;
    int 	ERR_WLS_SOCKETOVERRUN=264;
    int 	ERR_WLS_OTHERR=265;
    int 	ERR_CONNECT_TIMEOUT=266;
    int 	ERR_SETWIFIINFO=267;

    int 	ERR_TCP_TIMEOUT=268;
    int 	ERR_TCP_COMMERR=269;
    int 	ERR_TCP_SETLIP=270;
    int 	ERR_TCP_SETRIP=271;
    int 	ERR_TCP_SETRPORT=272;
    int 	ERR_TCP_CONN=273;
    int 	ERR_TCP_TXD=274;
    int 	ERR_TCP_RXD=275;
    int 	ERR_TCP_SETGW=276;
    int 	ERR_TCP_PARAM=278;
    int 	ERR_COMMS_INITCOM=279;//串口初始化失败
    int 	ERR_COMTYPE=280;//串口类型错误

    int 	EMVERROR_BYPASS=281;//BYPASS没有密码或用户忽略了密码输入

    //TAG
    int 	EMVTAGERR_OVERFLOW=282;
    int 	EMVTAGERR_PARAM=283;
    int 	EMVTAGERR_TAGNOTEXIST=284;
    int 	EMVTAGERR_DATA=285;
    int 	EMVTAGERR_PROPERTY=286;
    int 	EMVTAGERR_TAGLEN=287;
    int 	EMVTAGERR_TAGEXIST=288;
    int 	EMVTAGERR_DUPLICATE=289;

//


    int 	ERR_DEFIND_END=290;//定义结束




    }
